<?php
/**
 * @file
 * Implements valghalla cpr validation with serviceplatformen.dk
 *
 * @author Thomas Thune Hansen <tth@bellcom.dk>
 * @copyright 2012 OS2 - Offentligt Digitaliseringsfællesskab.
 * See README.md at https://github.com/os2web/valghalla_mail
 */
/**
 * Implements hook_permission().
 */
function serviceplatformen_permission() {
  return array(
    'Administer serviceplatformen' => array(
      'title' => t('Administer serviceplatformen'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function serviceplatformen_menu() {
  $items['admin/config/services/serviceplatformen'] = array(
    'title' => 'Indstillinger for serviceplatformen.dk',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('serviceplatformen_settings'),
    'access arguments' => array('Administer serviceplatformen'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_validator_cpr_service().
 */
function serviceplatformen_validator_cpr_service() {
  return array(
    'serviceplatformen' => array(
      // Label for the plugin, shown in CPR validator settings.
      'label' => 'serviceplatformen.dk',
      // Short description for the plugin, shown in CPR validator settings.
      'description' => t('Implements serviceplatformen.dk CPRBasicInformation'),
      // If the plugin implements CPR validation, the callback must be
      // specified here.
      'validate_cpr' => 'serviceplatformen_validate_cpr',
      // Same as above, but just for fetching the address for the
      // volunteer.
      'get_address' => 'serviceplatformen_get_address',
      // Url for plugin configuration.
      'config' => 'admin/config/services/serviceplatformen',
      // Get cpr form volunteer info.
      'get_cpr' => 'serviceplatformen_get_cpr',
    ),
  );
}

/**
 * Page callback for settings.
 */
function serviceplatformen_settings() {
  $form['stam'] = array(
    '#title' => 'Person stamdata',
    '#type' => 'fieldset',
  );
  
  $form['library'] = array(
    '#title' => 'Library data',
    '#type' => 'fieldset',
  );

  $form['library']['serviceplatformen_libra_ip'] = array(
    '#type' => 'textfield',
    '#title' => 'Libra ip fx. (10.0.0.10)',
    '#maxlength' => 15,
    '#default_value' => variable_get('serviceplatformen_libra_ip', ''),
  );
  
  $form['library']['serviceplatformen_libra_port'] = array(
    '#type' => 'textfield',
    '#title' => 'Libra port fx. (1721)',
    '#maxlength' => 4,
    '#default_value' => variable_get('serviceplatformen_libra_port', ''),
  );
  
 $form['library']['serviceplatformen_our_municipalno'] = array(
    '#type' => 'textfield',
    '#title' => 'Our municipal no. fx. (461)',
    '#maxlength' => 3,
    '#default_value' => variable_get('serviceplatformen_our_municipalno', ''),
  );
  
  $form['library']['serviceplatformen_adults_ours'] = array(
    '#type' => 'textfield',
    '#title' => 'Adults borrower category in our municipal fx. (vo)',
    '#maxlength' => 2,
    '#default_value' => variable_get('serviceplatformen_adults_ours', ''),
  );
  
  $form['library']['serviceplatformen_adults_notours'] = array(
    '#type' => 'textfield',
    '#title' => 'Adults borrower category NOT in our municipal fx. (vm)',
    '#maxlength' => 2,
    '#default_value' => variable_get('serviceplatformen_adults_notours', ''),
  );
  
  $form['library']['serviceplatformen_children_ours'] = array(
    '#type' => 'textfield',
    '#title' => 'Children borrower category in our municipal fx. (bo)',
    '#maxlength' => 2,
    '#default_value' => variable_get('serviceplatformen_children_ours', ''),
  );
  
  $form['library']['serviceplatformen_children_notours'] = array(
    '#type' => 'textfield',
    '#title' => 'Children borrower category NOT in our municipal fx. (bm)',
    '#maxlength' => 2,
    '#default_value' => variable_get('serviceplatformen_children_notours', ''),
  );

  $form['stam']['serviceplatformen_serviceagreementuuid'] = array(
    '#type' => 'textfield',
    '#title' => 'Serviceaftale UUID',
    '#default_value' => variable_get('serviceplatformen_serviceagreementuuid', ''),
  );

  $form['stam']['serviceplatformen_serviceuuid'] = array(
    '#type' => 'textfield',
    '#title' => 'Service UUID',
    '#default_value' => variable_get('serviceplatformen_serviceuuid', ''),
  );

  $form['stam']['serviceplatformen_wsdl'] = array(
    '#type' => 'textfield',
    '#title' => 'Service WSDL location',
    '#default_value' => variable_get('serviceplatformen_wsdl', ''),
    '#description' => t('ex. https://exttestwww.serviceplatformen.dk/administration/wsdl/CPRBasicInformationService.wsdl'),
  );

  $form['stam']['serviceplatformen_location'] = array(
    '#type' => 'textfield',
    '#title' => 'Service location',
    '#default_value' => variable_get('serviceplatformen_location', ''),
    '#description' => t('ex. https://exttest.serviceplatformen.dk/service/CPRBasicInformation/CPRBasicInformation/1'),
  );

  $form['adrsog'] = array(
    '#title' => 'ADRSOG1',
    '#type' => 'fieldset',
  );

  $form['adrsog']['serviceplatformen_adrsog_serviceagreementuuid'] = array(
    '#type' => 'textfield',
    '#title' => 'Serviceaftale UUID',
    '#default_value' => variable_get('serviceplatformen_adrsog_serviceagreementuuid', ''),
  );

  $form['adrsog']['serviceplatformen_adrsog_serviceuuid'] = array(
    '#type' => 'textfield',
    '#title' => 'Service UUID',
    '#default_value' => variable_get('serviceplatformen_adrsog_serviceuuid', ''),
  );

  $form['adrsog']['serviceplatformen_adrsog_location'] = array(
    '#type' => 'textfield',
    '#title' => 'Service location',
    '#default_value' => variable_get('serviceplatformen_adrsog_location', ''),
    '#description' => t('ex. https://exttest.serviceplatformen.dk/service/CPRBasicInformation/CPRBasicInformation/1'),
  );

  $form['serviceplatformen_usersystemuuid'] = array(
    '#type' => 'textfield',
    '#title' => 'System UUID',
    '#default_value' => variable_get('serviceplatformen_usersystemuuid', ''),
  );

  $form['serviceplatformen_useruuid'] = array(
    '#type' => 'textfield',
    '#title' => 'Kommune UUID',
    '#default_value' => variable_get('serviceplatformen_useruuid', ''),
  );

  $form['serviceplatformen_accountinginfo'] = array(
    '#type' => 'textfield',
    '#title' => 'AccountingInfo',
    '#default_value' => variable_get('serviceplatformen_accountinginfo', ''),
  );

  $form['serviceplatformen_certfile_passphrase'] = array(
    '#type' => 'password',
    '#title' => 'Certfile passphrase',
    '#default_value' => variable_get('serviceplatformen_certfile_passphrase', ''),
  );

  $form['serviceplatformen_certfile'] = array(
    '#type' => 'textfield',
    '#title' => 'Certfile',
    '#default_value' => variable_get('serviceplatformen_certfile', ''),
  );

  $form = system_settings_form($form);
  array_unshift($form['#submit'], 'serviceplatformen_settings_submit');

  return $form;
}

/**
 * Extra submit handler for serviceplatformen settings.
 */
function serviceplatformen_settings_submit(&$form, &$form_state) {
  if ($form_state['values']['serviceplatformen_certfile_passphrase'] == '') {
    unset($form_state['values']['serviceplatformen_certfile_passphrase']);
  }
}

/**
 * Validate cpr callback.
 *
 * @cpr String - PSN (cpr) ([0-9]{6}\-[0-9]{4})
 *
 * @return array
 *   [status] => TRUE/FALSE
 *   [text] => Descriptive text shown when CPR doesn't validate
 */
function serviceplatformen_validate_cpr($cpr) {
  return serviceplatformen_query($cpr);
}

/**
 * Query the webservice.
 */
function serviceplatformen_query($cpr) {
  ini_set('soap.wsdl_cache_enabled', 0);
  ini_set('soap.wsdl_cache_ttl', 0);

  try {
    $wsdl_address = variable_get('serviceplatformen_wsdl');
    $service_location = variable_get('serviceplatformen_location');
    $certfile_passphrase = variable_get('serviceplatformen_certfile_passphrase');
    $certfile = variable_get('serviceplatformen_certfile');

    $client = new SoapClient($wsdl_address, array(
      'location' => $service_location,
      'local_cert' => $certfile,
      'passphrase' => $certfile_passphrase,
      'trace' => TRUE,
    ));

    $serviceagreementuuid = variable_get('serviceplatformen_serviceagreementuuid');
    $usersystemuuid = variable_get('serviceplatformen_usersystemuuid');
    $useruuid = variable_get('serviceplatformen_useruuid');
    $serviceuuid = variable_get('serviceplatformen_serviceuuid');
    $accountinginfo = variable_get('serviceplatformen_accountinginfo');
    global $user;
    $onbehalfofuser = $user->name;

    $pnr = str_replace('-', '', $cpr);

    $request = array(
      'InvocationContext' => array(
        'ServiceAgreementUUID' => $serviceagreementuuid,
        'UserSystemUUID' => $usersystemuuid,
        'UserUUID' => $useruuid,
        'ServiceUUID' => $serviceuuid,
        'AccountingInfo' => $accountinginfo,
        'OnBehalfOfUser' => $onbehalfofuser,
      ),
      'PNR' => $pnr,
    );

    $response = (array) $client->callCPRBasicInformationService($request);

    $response['status'] = TRUE;
    return $response;

  }
  catch (Exception $e) {
    list($fault, $message) = explode(':', $e->faultstring);

    if (!$message) {
      $message = $e->faultstring;
    }

    return array(
      'status' => FALSE,
      'text' => $message,
    );
  }
}

/**
 * Fetch address for the specified CPR.
 *
 * @cpr
 *  String - PSN (cpr) ([0-9]{6}\-[0-9]{4})
 *
 * @return array
 *   [status] => TRUE/FALSE
 *   [address] => Roadname 10
 *   [zipcode] => 1212
 *   [text] => Descriptive text if something goes wrong
 */
function serviceplatformen_get_address($cpr) {
  $message = serviceplatformen_get_cpr($cpr);

  // If all goes well we return de address as valghalla wants it.
  if ($message['status']) {
    return array(
      'status' => TRUE,
      'cpr' => isset($message['cpr']) ? $message['cpr'] : '',
      'name' => isset($message['adresseringsnavn']) ? $message['adresseringsnavn'] : '',
      'road' => isset($message['vejadresseringsnavn']) ? $message['vejadresseringsnavn'] : '',
      //'road_no' => isset($message['husnummer']) ? $message['husnummer'] : '',
      //'floor' => isset($message['etage']) ? $message['etage'] : '',
      //'door' => isset($message['sidedoer']) ? $message['sidedoer'] : '',
      'zipcode' => isset($message['postnummer']) ? $message['postnummer'] : '',
      'postdistrikt' => isset($message['postdistrikt']) ? $message['postdistrikt'] : '',
      //'FOEDDATO' => isset($message['FOEDDATO']) ? $message['FOEDDATO'] : '',
      'KOMKOD' => isset($message['KOMKOD']) ? $message['KOMKOD'] : '',
    );
  }
  else {
    return $message;
  }
}

/**
 * Get CPR for specified address and name.
 */
function serviceplatformen_get_cpr($cpr) {
    $service_location = variable_get('serviceplatformen_location');
    $certfile_passphrase = variable_get('serviceplatformen_certfile_passphrase');
    $certfile = variable_get('serviceplatformen_certfile');

  // ADRSOG1 specific uuids.
  $serviceagreementuuid = variable_get('serviceplatformen_serviceagreementuuid');
  $serviceuuid = variable_get('serviceplatformen_serviceuuid');
  // Generic/municipality uuids.
  $usersystemuuid = variable_get('serviceplatformen_usersystemuuid');
  $useruuid = variable_get('serviceplatformen_useruuid');
  // Extra info.
  $accountinginfo = variable_get('serviceplatformen_accountinginfo');
  global $user;
  $onbehalfofuser = $user->name;

  // Generate gctp message.
  $message_start = '<Gctp v="1.0"><System r="CprSoeg"><Service r="Familie+"><CprServiceHeader r="Familie+"><Key>';

  $message_fields = '
    <Field r="PNR" v="' . $cpr . '"/>';

  $message_end = '</Key></CprServiceHeader></Service></System></Gctp>';

  $mess = $message_start . $message_fields . $message_end;

  // Entire xml post string.
  $xml_post_string = <<<EOL
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:kom="http://serviceplatformen.dk/xml/wsdl/soap11/CprService/2/" xmlns:invctx="http://serviceplatformen.dk/xml/schemas/InvocationContext/1/">
  <soapenv:Header/>
  <soapenv:Body>
    <kom:callGCTPCheckServiceRequest>
      <invctx:InvocationContext>
        <invctx:ServiceAgreementUUID>$serviceagreementuuid</invctx:ServiceAgreementUUID>
        <invctx:UserSystemUUID>$usersystemuuid</invctx:UserSystemUUID>
        <invctx:UserUUID>$useruuid</invctx:UserUUID>
        <invctx:ServiceUUID>$serviceuuid</invctx:ServiceUUID>
        <invctx:OnBehalfOfUser>$serviceuuid</invctx:OnBehalfOfUser>
        <invctx:AccountingInfo>$serviceuuid</invctx:AccountingInfo>
      </invctx:InvocationContext>
      <kom:gctpMessage>
        <![CDATA[
$mess
]]>
      </kom:gctpMessage>
    </kom:callGCTPCheckServiceRequest>
  </soapenv:Body>
</soapenv:Envelope>
EOL;

  try {
    // Curl call to service.
    $headers = array(
      "Content-type: text/xml;charset=\"utf-8\"",
      "Accept: text/xml",
      "Cache-Control: no-cache",
      "Pragma: no-cache",
      "Content-length: " . strlen($xml_post_string),
    );

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $service_location);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
    curl_setopt($ch, CURLOPT_POST, TRUE);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $xml_post_string);
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    curl_setopt($ch, CURLOPT_SSLCERT, $certfile);
    curl_setopt($ch, CURLOPT_SSLCERTPASSWD, $certfile_passphrase);
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $response = curl_exec($ch);

    // If no theres no response from the service, return an error.
    if (!$response) {
      return array(
        'status' => 'error',
      );
    }

    curl_close($ch);

    $xml = simplexml_load_string($response);
    $xml->registerXPathNamespace('ns2', 'http://serviceplatformen.dk/xml/wsdl/soap11/CprService/2/');

    $gctp = $xml->xpath('//ns2:result');

    $xml = simplexml_load_string(end($gctp));

    // Init variables.
    $result_row = FALSE;
    $cpr = FALSE;
    $name = FALSE;

    // Go through the resulting rows.
    foreach ($xml->Gctp->System->Service->CprData->Rolle->Table->Row as $row) {
      $row_attributes = (array) $row->attributes();

      foreach ($row->Field as $delta => $field) {
        $attributes = (array) $field->attributes();

        // Check if the first name of cpr matches data in response.
        if ($attributes['@attributes']['r'] == 'CNVN_ADRNVN') {
          if (serviceplatformen_match_name($attributes['@attributes']['t'], $cpr['PNR'])) {
            $name = TRUE;
            $result_row = (array) $row;
          }

        }
        }
      }


    if ($result_row) {
      foreach ($result_row['Field'] as $field) {
        $attributes = (array) $field->attributes();

        if ($attributes['@attributes']['r'] == 'PNR') {
          $cpr = $attributes['@attributes']['v'];
        }
        if ($attributes['@attributes']['r'] == 'CNVN_ADRNVN') {
            $navn = $attributes['@attributes']['v'];
        }
        if ($attributes['@attributes']['r'] == 'STADR') {
            $road = $attributes['@attributes']['v'];
        }
        if ($attributes['@attributes']['r'] == 'BYNVN') {
            $postdistrikt = $attributes['@attributes']['v'];
        }
        if ($attributes['@attributes']['r'] == 'POSTNR') {
            $zipcode = $attributes['@attributes']['v'];
        }
        if ($attributes['@attributes']['r'] == 'KOMKOD') {
            $KOMKOD = $attributes['@attributes']['v'];
        }
        /*
        if ($attributes['@attributes']['r'] == 'FOEDDATO') {
            $FOEDDATO = $attributes['@attributes']['v'];
        }
        */
      }

    if ($navn) {
        return array(
            'status' => 'success',
            'cpr' => $cpr,
            'adresseringsnavn' => $navn,
            'vejadresseringsnavn' => $road,
            'postdistrikt' => $postdistrikt,
            'postnummer' => $zipcode,
            'KOMKOD' => $KOMKOD,
            //'FOEDDATO' => $FOEDDATO,
        );
    }
    else {
      return array(
        'status' => 'not found',
      );
    }


    }

  }
  catch (Exception $e) {
    error_log(__FILE__ . ' : ' . __LINE__ . ': ' .  print_r($e, 1));

    return array(
      'status' => 'error',
    );
  }
}

/**
 * Match birthdate to part of PSN from serviceplatformen.
 */
function serviceplatformen_match_cpr($value, $find) {
  $reg_birthdate = substr($value, 0, 6);

  return $reg_birthdate == $find;
}

/**
 * Match name from serviceplatformen to the volunteers name.
 */
function serviceplatformen_match_name($value, $find) {
  $value_array = explode(' ', $value);
  $find_array = explode(' ', $find);

  return strtolower($find_array[0]) == strtolower($value_array[0]);
}
